In [71]:
### softmax(), sigmoid() 함수
# - sigmoid() : y=wx+b 결과 1개 전달, y값을 0~1사이의 값으로 변환
# - softmax() : y=wx+b 결과 여러개 전달 , y값을 0~1사이의 값으로 변환, 모든 출력의 합이 1이 되도록 변환

In [72]:
import torch
import torch.nn.functional as F


In [73]:
data1=torch.tensor([1,2,1,1,2])

In [74]:
F.sigmoid(data1)

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [75]:
data2=data1.unsqueeze(dim=0)
data2.shape, data2

(torch.Size([1, 5]), tensor([[1, 2, 1, 1, 2]]))

In [76]:
input = torch.randn(2,3)
F.softmax(input).max(dim=1)[1][0].item()
# argmax는 인덱스만 준다 

C:\Users\mathn\AppData\Local\Temp\ipykernel_7464\3731823473.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(input).max(dim=1)[1][0].item()


1

In [91]:
data2=data2.float()
data2, data2.shape, data2[0]

(tensor([[1., 2., 1., 1., 2.]]),
 torch.Size([1, 5]),
 tensor([1., 2., 1., 1., 2.]))

In [93]:
F.softmax(data2[0],dim=0)

tensor([0.1185, 0.3222, 0.1185, 0.1185, 0.3222])