In [1]:
#  Tensor Shape 변경
# -reshape(), view() ; 원소 개수가 유지됨! 기존 텐서를 공유함

In [3]:
import torch

t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)

torch.Size([2, 3]) 2


In [4]:
t1.view(3,2) # 3x2 행렬로 변경

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
t1.view(-1,1) # 열을 하나로 고정하고, 나머지 데이터를 자동으로 해결하라는 뜻

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [6]:
t1.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [7]:
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
t1,t1.T

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [12]:
t1.T.view(-1,6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [13]:
t1.T.reshape(-1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [15]:
t1.T.is_contiguous(), t1.is_contiguous()

(False, True)

In [16]:
t1.T.contiguous().view(-1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [18]:
t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)
print(t1.storage())
print("offset",t1.storage_offset())
print(t1.stride())

torch.Size([2, 3]) 2
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
offset 0
(3, 1)
