In [2]:
# 파이썬 버전, pytorch 버전, pandas버전, matplotlib버전, seaborn 버전, numpy버전 확인
import sys
import torch
import pandas as pd
import matplotlib
import seaborn as sns
import numpy as np
import sklearn


In [3]:
print(sys.version)
print(torch.__version__)
print(pd.__version__)
print(matplotlib.__version__)
print(sns.__version__)
print(np.__version__)
print(sklearn.__version__)

3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2.2.0
2.0.3
3.7.2
0.12.2
1.24.3
1.3.0


In [4]:
# 해당 PC에 GPU 사용 가능 여부 확인
print(f'GPU => {torch.cuda.is_available()}')

GPU => False


In [5]:
# 텐서(Tensor) 살펴보기
# - Pytorch에서 데이터 저장 자료형
# - 모델 입력(input), 출력(output) 데이터 형태

In [6]:
import torch
def print_attribute(tensor, name):
    print(f"[Tensor {name}]\s Attribute")
    print(f" - tensor.shape : {tensor.shape}")
    print(f" - tensor.ndim : {tensor.ndim}")
    print(f" - tensor.dtype : {tensor.dtype}")
    print(f" - tensor.device : {tensor.device}")
    print(f" - tensor.requies_grad : {tensor.requires_grad}")
    print(f" - tensor.data \n: {tensor.data}")

In [7]:
# 정수 타입 텐서 생성
t1=torch.IntTensor(10)
t2=torch.IntTensor([10,20])


In [8]:
print_attribute(t1,'t1')
print_attribute(t2,'t2')

[Tensor t1]\s Attribute
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
[Tensor t2]\s Attribute
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([10, 20], dtype=torch.int32)


In [9]:
t3=torch.BoolTensor([1,1,-1,0])
print_attribute(t3,'t3')

[Tensor t3]\s Attribute
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([ True,  True,  True, False])


In [10]:
t4=torch.FloatTensor([1,1,-1,0])
print_attribute(t4,'t4')

[Tensor t4]\s Attribute
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([ 1.,  1., -1.,  0.])


In [11]:
# Tensor 생성 : 원하는 값으로 텐서 생성 => torch.tensor()
t1=torch.tensor(10)
print_attribute(t1,'t1') # 자동으로 int64로 생성

[Tensor t1]\s Attribute
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: 10


In [12]:
t2=torch.tensor(10.)
print_attribute(t2,'t2')

[Tensor t2]\s Attribute
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: 10.0


In [13]:
t2=torch.tensor(10., dtype=torch.int32) # 강제적으로 변경
print_attribute(t2,'t2')

[Tensor t2]\s Attribute
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: 10


C:\Users\mathn\AppData\Local\Temp\ipykernel_23556\955552128.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2=torch.tensor(10., dtype=torch.int32) # 강제적으로 변경


In [14]:
t3=torch.tensor([[1,2,3]], dtype=torch.int8) # 강제적으로 변경
print_attribute(t3,'t3')

[Tensor t3]\s Attribute
 - tensor.shape : torch.Size([1, 3])
 - tensor.ndim : 2
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([[1, 2, 3]], dtype=torch.int8)


In [15]:
# Tensor 생성 기술


In [16]:
t1=torch.zeros((5,5), dtype=torch.int8)
print_attribute(t1,'t1')

[Tensor t1]\s Attribute
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [17]:
t2=torch.ones((5,5), dtype=torch.int8)
print_attribute(t2,'t2')

[Tensor t2]\s Attribute
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requies_grad : False
 - tensor.data 
: tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)


In [18]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
torch.ones_like(torch.tensor([[1,2,3,4,5,6],[9,8,7,6,5,5]]))

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [19]:
torch.full_like(torch.tensor([[1,2,3,4,5,6],[9,8,7,6,5,5]]),7)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])

In [20]:
torch.manual_seed ( 12 ) # 랜덤 초기값 설정
torch.rand( 2, 3 ).data

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])

In [21]:
torch.randn( 2, 3).data

tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])

In [22]:
torch.randint( low=1, high=10, size=(2,3) ).data

tensor([[8, 4, 6],
        [2, 2, 2]])

In [23]:
import numpy as np
arr = np.array ( [1,3,5] ) # ndarray 객체
t1 = torch.from_numpy( arr ) # Sharing
t2 = torch.as_tensor( arr ) # Sharing
t3 = torch.tensor( arr ) # Copy

In [24]:
# ndarray 객체의 값 변경
arr[0]=100
t1,t2,t3

(tensor([100,   3,   5], dtype=torch.int32),
 tensor([100,   3,   5], dtype=torch.int32),
 tensor([1, 3, 5], dtype=torch.int32))

In [25]:
torch.arange(2) # 0<= ~ < 2 1간격
torch.arange(1,10) # 1<= ~ < 10 1간격
torch.arange(1,10,3) # 1<= ~ < 10 3간격

tensor([1, 4, 7])

In [26]:
# 인덱싱과 슬라이싱
import torch

points=torch.tensor([[4.,2.],[5.,3.],[6.,7.]], dtype=torch.int16)
points

C:\Users\mathn\AppData\Local\Temp\ipykernel_23556\2758694134.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points=torch.tensor([[4.,2.],[5.,3.],[6.,7.]], dtype=torch.int16)


tensor([[4, 2],
        [5, 3],
        [6, 7]], dtype=torch.int16)

In [27]:
# 데이터 3 추출
points[1,1]

tensor(3, dtype=torch.int16)

In [28]:
# 1번 행부터 나머지 모든 행 추출
for i in points:
    for j in i:
        print(j)

tensor(4, dtype=torch.int16)
tensor(2, dtype=torch.int16)
tensor(5, dtype=torch.int16)
tensor(3, dtype=torch.int16)
tensor(6, dtype=torch.int16)
tensor(7, dtype=torch.int16)


In [29]:
# Case 1 : 같은 크기 행렬
m1 = torch.FloatTensor([[3, 4]])
m2 = torch.FloatTensor([[2, 5]])
m3=m1+m2
print(m3, m3.shape)

tensor([[5., 9.]]) torch.Size([1, 2])


In [31]:
# Case 2 : 벡터와 행렬
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
m3 = m1 + m2
print(m3, m3.shape)

tensor([[4., 5.]]) torch.Size([1, 2])


In [32]:
# Case 3 : 크기 다른 두 개 행렬
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
m3 = m1 + m2
print(m3, m3.shape)

tensor([[4., 5.],
        [5., 6.]]) torch.Size([2, 2])


In [33]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print( m1 * m2 )
print( m1.mul( m2 ) )

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [35]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
m12= m1.matmul( m2 )
print( m12.data)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
