In [1]:
#  Tensor Shape 변경
# -reshape(), view() ; 원소 개수가 유지됨! 기존 텐서를 공유함

In [3]:
import torch

t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)

torch.Size([2, 3]) 2


In [4]:
t1.view(3,2) # 3x2 행렬로 변경

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
t1.view(-1,1) # 열을 하나로 고정하고, 나머지 데이터를 자동으로 해결하라는 뜻

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [6]:
t1.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [7]:
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
t1,t1.T

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [12]:
t1.T.view(-1,6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [13]:
t1.T.reshape(-1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [15]:
t1.T.is_contiguous(), t1.is_contiguous()

(False, True)

In [16]:
t1.T.contiguous().view(-1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [18]:
t1=torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)
print(t1.storage())
print("offset",t1.storage_offset())
print(t1.stride())

torch.Size([2, 3]) 2
 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
offset 0
(3, 1)


In [21]:
import numpy as np
a=np.array([[[1,2,3]]])
a.squeeze()

array([1, 2, 3])

In [22]:
# 차원 제거/추가
# tensor.squeeze() : 차원의 원소가 1인 차원을 제거
# tensor.unsqueeze() : 차원을 추가

In [23]:
t1=torch.tensor([[1,2],[3,4]])
t2=torch.tensor([[1,2,3,4]])

In [24]:
t11=t1.squeeze()
t22=t2.squeeze()

print(f"t1 차원 축소 => {t11.shape}, {t11.ndim}D")
print(f"t1 차원 축소 => {t22.shape}, {t22.ndim}D")

t1 차원 축소 => torch.Size([2, 2]), 2D
t1 차원 축소 => torch.Size([4]), 1D


In [25]:
ft = torch.FloatTensor([[0, 1, 2]])
print(ft)
print(ft.shape) # torch.Size([3])
ft2=ft.unsqueeze(0) # 인덱스 0번째 차원
print(ft2.shape) # torch.Size([1, 3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])
torch.Size([1, 1, 3])


In [34]:
t=torch.tensor([[[[1,2,3],[1,2,3]]]])
t.shape

torch.Size([1, 1, 2, 3])

In [36]:
t.squeeze(dim=[0,1]).shape

torch.Size([2, 3])

In [38]:
t=torch.tensor([1,2,3])
t.shape

torch.Size([3])

In [39]:
t.unsqueeze(0).shape

torch.Size([1, 3])

In [40]:
t.unsqueeze(-1).shape

torch.Size([3, 1])

In [41]:
lt = torch.LongTensor( [1, 2, 3, 4] )
print( lt.dtype, lt )
print( lt.float().dtype ) # float 타입으로 형변환
print( lt.char().dtype ) # char 타입으로 형변환
print( lt.double().dtype ) # double 타입으로 형변환
print( lt.bool().dtype ) # bool 타입으로 형변환

torch.int64 tensor([1, 2, 3, 4])
torch.float32
torch.int8
torch.float64
torch.bool


: 