In [13]:
import torch
torch.manual_seed(12)
X=torch.rand(2,10) # 2행 10열의 데이터 생성
y=torch.randint(0,2,(10,)) # 0<=x<2 범위의 정수 10개 생성
y2=torch.randint(0,2,(2,10)) # 0<=x<2 범위의 정수 2행 10열 생성

In [12]:
print(f"X=>{X.shape},{X.ndim}D")
print(f"y=>{y.shape},{y.ndim}D")

X=>torch.Size([2, 10]),2D
y=>torch.Size([10]),1D


In [15]:
torch.cat([X,y2], dim=1) # dim=1(열) 방향으로 연결

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224, 1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000]])

In [16]:
torch.cat([X,y2], dim=0) # dim=0(행) 방향으로 연결

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456],
        [1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [18]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
torch.stack([x, y, z])
#torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [19]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))


tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max(),"\n\n") # 최댓값 반환
print(t.max(dim=0)) # 해당 차원에서의 최댓값과, 인덱스 반환


tensor(4.) 


torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [24]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [25]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행
print(t.sum(dim=1)) # 열
print(t.sum(dim=-1)) # 열

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [26]:
# 차원 형태 변경
t1=torch.tensor([[[1, 2, 3],
                     [4, 5, 6]],
                    [[7, 8, 9],
                     [10, 11, 12]],
                    [[13, 14, 15],
                     [16, 17, 18]],
                    [[19, 20, 21],
                     [22, 23, 24]],
                    [[25, 26, 27],
                     [28, 29, 30]]])
t1.shape

torch.Size([5, 2, 3])

In [27]:
t11=t1.transpose(0,2)
t11.shape

torch.Size([3, 2, 5])

In [29]:
t11=t1.permute(1,2,0)
t11.shape

torch.Size([2, 3, 5])

In [31]:
t1[None].shape

torch.Size([1, 5, 2, 3])

In [32]:
import numpy as np
np.arange(1*2*3)

array([0, 1, 2, 3, 4, 5])

: 