In [ ]:
# 1. 화면상에서 Pytorch에서 데이터를 저장하는 단위는 "텐서"입니다
# 2. 텐서는 다차원 데이터를 담는 수학 객체이고, 모델 입력과 출력에 사용된다
     #NumPy와 유사하고, CPU와 GPU를 사용할 때 텐서 선언 방식이 다르다!

In [1]:
# 3. 정수형 데이터를 저장하는 데이터 타입 : 
# 8bit unsigned integer (Byte Tensor)
# 8bit integer (Char Tensor)
# 16bit integer (Short Tensor)
# 32bit integer (Int Tensor)
# 64bit integer (Long Tensor)

In [3]:
# 4. 
import torch
t=torch.BoolTensor([10,-5,1.4,7,0,-1,0])
#t의 모든 속성값을 출력
print(f'data => {t.data}')
print(f'shape => {t.shape}')
print(f'ndim => {t.ndim}')
print(f'type=> {t.dtype}')
print(f'device => {t.device}')
print(f'requres_grad => {t.requires_grad}')
print(f'is_floating_point => {t.is_floating_point}')

data => tensor([ True,  True,  True,  True, False,  True, False])
shape => torch.Size([7])
ndim => 1
type=> torch.bool
device => cpu
requres_grad => False
is_floating_point => <built-in method is_floating_point of Tensor object at 0x000001C5F72583B0>


In [12]:
# 5.
t=torch.Tensor([0 for _ in range(10)])
t=t.unsqueeze(-1)
t

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [11]:
# 6. 5개의 1데이터가 대각선으로 저장되는 2차원 저장 코드를 작성하세요
t=torch.eye(5)
t

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
# 7. 5번에서 저장된 형태와 동일하지만, 값이 3이 저장된 코드를 작성하시오 
torch.full_like(t,3)

tensor([[3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [18]:
# 8. ndarray데이터를 Pytorch에 저장하는 코드를 작성하세요
import numpy as np
data=np.array(range(7,100,7))
t=torch.from_numpy(data).type(torch.FloatTensor)
t.dtype, t.data

(torch.float32,
 tensor([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77., 84., 91., 98.]))

In [20]:
# 9. 아래 조건에 맞는 데이터르르 Pytorch 에 저장하는 코드를 작성하세요
# 이미지 파일 : flower.jpg 파일
# 이미지를 3차원 텐서로 저장

from PIL import Image
img=Image.open('flower.jpg')
t=torch.Tensor(np.array(img))
t.data, t.ndim

(tensor([[[255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.],
          ...,
          [255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.]],
 
         [[255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.],
          ...,
          [255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.]],
 
         [[255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.],
          ...,
          [255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.]],
 
         ...,
 
         [[255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.],
          ...,
          [255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.]],
 
         [[255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.],
          ...,
          [255., 255., 255.],
          [255., 255., 255.],
          [255., 255., 255.

In [28]:
# 10. 임의의 정수 10개
data=torch.randint(0,10,(10,)) # 10개 저장
data=data.unsqueeze(0)
data=data.unsqueeze(0)
data.transpose(1,2)  # 차원 2개를 바꿈


tensor([[[2],
         [8],
         [5],
         [1],
         [4],
         [2],
         [7],
         [5],
         [9],
         [2]]])

In [29]:
data.permute(0,2,1)  # 차원 3개를 바꿈

tensor([[[2],
         [8],
         [5],
         [1],
         [4],
         [2],
         [7],
         [5],
         [9],
         [2]]])

In [41]:
# 11. 아래 조건에 맞도록 코드를 작성하세요
data=torch.tensor([[90,70,80],[70,100,80],[99,88,77]], dtype=torch.float32)
# 과목별 합계
data.sum(dim=1)

tensor([240., 250., 264.])

In [42]:
# 과목별 최고점수
data.max(dim=1)[0]

tensor([ 90., 100.,  99.])

In [43]:
# 과목별 평균
data.mean()

tensor(83.7778)

In [44]:
# 한 사람의 점수 합계
data.sum(dim=0)

tensor([259., 258., 237.])

In [45]:
# 한 사람의 점수 평균
data.mean(dim=0)

tensor([86.3333, 86.0000, 79.0000])

In [47]:
# 한 사람의 최고점수
data.max(dim=0)[0]

tensor([ 99., 100.,  80.])

In [52]:
# 12. 아래 조건에 맞도록 코드를 작성하세요
# data : 3행 3열, data2 : 1행 3열 텐서를 생성하고, 사칙연산 결과를 출력하세요

data2=torch.tensor([0.5,0.2,0.7])
# 사칙연산 결과
print(f"더하기 : {data+data2}\n")
print(f"빼기 : {data-data2}\n")
print(f"나누기 : {data/data2}\n")
print(f"곱하기 : {data*data2}\n")

더하기 : tensor([[ 90.5000,  70.2000,  80.7000],
        [ 70.5000, 100.2000,  80.7000],
        [ 99.5000,  88.2000,  77.7000]])

빼기 : tensor([[89.5000, 69.8000, 79.3000],
        [69.5000, 99.8000, 79.3000],
        [98.5000, 87.8000, 76.3000]])

나누기 : tensor([[180.0000, 350.0000, 114.2857],
        [140.0000, 500.0000, 114.2857],
        [198.0000, 440.0000, 110.0000]])

곱하기 : tensor([[45.0000, 14.0000, 56.0000],
        [35.0000, 20.0000, 56.0000],
        [49.5000, 17.6000, 53.9000]])



In [50]:
data.matmul(data2)

tensor([115., 111., 121.])